# Generated by Django 5.0.6 on 2024-07-21 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0002_etudiant_pointage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointage',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='pointage',
            name='etudiant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pointage.etudiant'),
        ),
    ]
