# Generated by Django 5.0.6 on 2024-07-21 12:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointage', '0003_remove_pointage_employee_id_pointage_etudiant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointage',
            name='etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pointage.etudiant'),
        ),
    ]
